### ISSUE TITLE
Demo works but not able to get working in another process

### ISSUE THREAD

**Issue by cybrpimp** [StephenOTT/camunda-formio-plugin#40]
I have been trying for weeks to get this working in one of our custom forms.  The Demo works great and I'm using it as a reference.

Here is the current error we are getting when we submit the form in our custom process.

![image_2020_10_12T08_37_22_244Z](https://user-images.githubusercontent.com/61793417/95725755-a361c780-0caa-11eb-9407-f1bafd34b37a.png)

Here is our setting in the Modeler.

![image](https://user-images.githubusercontent.com/61793417/95726040-fd628d00-0caa-11eb-91e5-34b2aad5171a.png)

I'm still not sure how the `var` is used.  In an attempt to understand better, I searched in the Demo Process XML and the form JSON for "noPersitSubmission" but still puzzled exactly how to use the var parameter, but I'm not sure if this has anything to do with the error or not.

**Comment by StephenOTT** [comment]
The docs explain how the `var` is used:
https://github.com/StephenOTT/camunda-formio-plugin#configuration-options

>Define a custom variable name for the form submission. Will be submitted as a Process Variable.

You need to provide more error info from the console to debug further.

**Comment by cybrpimp** [comment]
Ok, thanks!  So just to clarify, the var is the Process Variable Name that is created upon submit of the form.

Here is the Tracestack for this error...

`
12-Oct-2020 01:37:14.886 SEVERE [http-nio-8081-exec-8] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context: Unable to find a JSON variable in the Tasklist submission
	org.camunda.bpm.engine.impl.form.validator.FormFieldConfigurationException: Unable to find a JSON variable in the Tasklist submission
		at com.github.stephenott.camunda.formio.FormioFormFieldValidator.validate(FormioFormFieldValidator.kt:22)
		at org.camunda.bpm.engine.impl.form.handler.FormFieldValidationConstraintHandler.validate(FormFieldValidationConstraintHandler.java:51)
		at org.camunda.bpm.engine.impl.form.handler.FormFieldHandler.handleSubmit(FormFieldHandler.java:130)
		at org.camunda.bpm.engine.impl.form.handler.DefaultFormHandler.submitFormVariables(DefaultFormHandler.java:298)
		at org.camunda.bpm.engine.impl.form.handler.SubmitFormVariablesInvocation.invoke(SubmitFormVariablesInvocation.java:42)
		at org.camunda.bpm.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:58)
		at org.camunda.bpm.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocationInContext(DefaultDelegateInterceptor.java:92)
		at org.camunda.bpm.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:63)
		at org.camunda.bpm.engine.impl.form.handler.DelegateFormHandler$2.call(DelegateFormHandler.java:83)
		at org.camunda.bpm.engine.impl.form.handler.DelegateFormHandler$2.call(DelegateFormHandler.java:79)
		at org.camunda.bpm.engine.impl.form.handler.DelegateFormHandler.doCall(DelegateFormHandler.java:70)
		at org.camunda.bpm.engine.impl.form.handler.DelegateFormHandler.performContextSwitch(DelegateFormHandler.java:64)
		at org.camunda.bpm.engine.impl.form.handler.DelegateFormHandler.submitFormVariables(DelegateFormHandler.java:79)
		at org.camunda.bpm.engine.impl.cmd.SubmitTaskFormCmd.execute(SubmitTaskFormCmd.java:75)
		at org.camunda.bpm.engine.impl.cmd.SubmitTaskFormCmd.execute(SubmitTaskFormCmd.java:43)
		at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)
		at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:110)
		at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70)
		at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
		at org.camunda.bpm.engine.impl.FormServiceImpl.submitTaskForm(FormServiceImpl.java:91)
		at org.camunda.bpm.engine.rest.sub.task.impl.TaskResourceImpl.submit(TaskResourceImpl.java:148)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
		at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257)
		at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222)
		at org.jboss.resteasy.core.ResourceLocator.invokeOnTargetObject(ResourceLocator.java:159)
		at org.jboss.resteasy.core.ResourceLocator.invoke(ResourceLocator.java:107)
		at org.jboss.resteasy.core.ResourceLocator.invokeOnTargetObject(ResourceLocator.java:154)
		at org.jboss.resteasy.core.ResourceLocator.invoke(ResourceLocator.java:92)
		at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:542)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
		at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
		at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
		at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.camunda.bpm.engine.rest.filter.CacheControlFilter.doFilter(CacheControlFilter.java:45)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.camunda.bpm.engine.rest.filter.EmptyBodyFilter.doFilter(EmptyBodyFilter.java:99)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.camunda.bpm.webapp.impl.security.filter.headersec.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:87)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.camunda.bpm.webapp.impl.security.filter.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:175)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.camunda.bpm.webapp.impl.security.filter.SecurityFilter.doFilterSecure(SecurityFilter.java:71)
		at org.camunda.bpm.webapp.impl.security.filter.SecurityFilter.doFilter(SecurityFilter.java:55)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.camunda.bpm.webapp.impl.security.auth.AuthenticationFilter$1.execute(AuthenticationFilter.java:62)
		at org.camunda.bpm.webapp.impl.security.auth.AuthenticationFilter$1.execute(AuthenticationFilter.java:60)
		at org.camunda.bpm.webapp.impl.security.SecurityActions.runWithAuthentications(SecurityActions.java:44)
		at org.camunda.bpm.webapp.impl.security.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:60)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:352)
		at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Unknown Source)
	Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
		at com.github.stephenott.camunda.formio.FormioFormFieldValidator.validate(FormioFormFieldValidator.kt:80)
`

**Comment by StephenOTT** [comment]
@cybrpimp please try : https://github.com/StephenOTT/camunda-formio-plugin/blob/v1.5/docker/docker-compose.yml

and test your custom BPMN and deployed files through the docker compose.  

The docker compose sets up the Validation server and network between Camunda and Formio Validation Server.

**Comment by StephenOTT** [comment]
@cybrpimp were you able to make progress?

**Comment by StephenOTT** [comment]
please reopen if you continue to have issues
